#ifndef TOKEN_H
#define TOKEN_H


enum TokenType {
    NOTHING_TOKEN = 0,
    CCOMMENT_TOKEN,
    CPPCOMMENT_TOKEN,
    CHAR_TOKEN,
    STRING_TOKEN,
    INT_TOKEN,
    FLOAT_TOKEN,
    ID_TOKEN,
    ERROR_TOKEN,
    SEMICOLON_TOKEN,
    GREATER_OR_EQ_TOKEN,
    GREATER_TOKEN,
    LESS_OR_EQ_TOKEN,
    LESS_TOKEN,
    ASSERT_EQ_TOKEN,
    KEYWORD_TOKEN,
    POWER_TOKEN,
    ADDITION_TOKEN,
    SUBTRACTION_TOKEN,
    DIVISION_TOKEN,
    NOT_EQUAL_TOKEN,
    OR_TOKEN,
    AND_TOKEN,
    NOT_TOKEN,
    MULTIPLY_TOKEN,
    MODULO_TOKEN,
    COLON_TOKEN,
    OPEN_PARAN_TOKEN,
    CLOSE_PARAN_TOKEN
};

const char* TokenNames[] = {
    "NOTHING_TOKEN",
    "CCOMMENT_TOKEN",
    "CPPCOMMENT_TOKEN",
    "CHAR_TOKEN",
    "STRING_TOKEN",
    "INT_TOKEN",
    "FLOAT_TOKEN",
    "ID_TOKEN",
    "ERROR_TOKEN",
    "SEMICOLON_TOKEN",
    "GREATER_OR_EQ_TOKEN",
    "GREATER_TOKEN",
    "LESS_OR_EQ_TOKEN",
    "LESS_TOKEN",
    "ASSERT_EQ_TOKEN",
    "KEYWORD_TOKEN",
    "POWER_TOKEN",
    "ADDITION_TOKEN",
    "SUBTRACTION_TOKEN",
    "DIVISION_TOKEN",
    "NOT_EQUAL_TOKEN",
    "OR_TOKEN",
    "AND_TOKEN",
    "NOT_TOKEN",
    "MULTIPLY_TOKEN",
    "MODULO_TOKEN",
    "COLON_TOKEN",
    "OPEN_PARAN_TOKEN",
    "CLOSE_PARAN_TOKEN"
};

#endif